name: checker grid

on:
  push:
  schedule:
    - cron: "0 0 */2 * *"  # Run every 2 days

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          the_time=$(date +'%Y %b %e, %l:%M %p')
          echo "Time: $the_time" > foo.txt
          git config user.name "checker-grid"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"  # ref: https://stackoverflow.com/a/72981982/22294664   https://stackoverflow.com/questions/69839851/github-actions-copy-git-user-name-and-user-email-from-last-commit
          git commit -am "New tile @ $the_time"
          git push
