name: checker grid

on:
  schedule:
    - cron: "0 0 */2 * *"  # Run every 2 days

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3  
      - name: run
        run: |
          echo "Today is: $(date +%F)" > foo.txt
          git config user.name "checker-grid"
          git config user.email "111596906+nvfastplease@users.noreply.github.com"
          git add .
          git commit -m "New tile @ $(date +'%Y %b %e, %l:%M %p')"
          git push
